version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # Main LocalStack API gateway
      - "4571:4571" # For additional services if needed
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,lambda,dynamodb,apigateway,ec2,sqs,sns,cloudwatch # Add desired AWS services
      - DEBUG=1 # Optional: Enable debug logs
    volumes:
      - ./localstack_data:/var/lib/localstack # Persist data locally
      - /var/run/docker.sock:/var/run/docker.sock

